############################################
# Variables
############################################

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

variable "instance_name" {
  description = "Name tag for the EC2 instance"
  type        = string
  default     = "my_app_instance"
}

variable "key_name" {
  description = "Name of the AWS key pair to create/attach"
  type        = string
  default     = "my_app_instance_key"
}

variable "allowed_ssh_cidr" {
  description = "CIDR block allowed to SSH in. Restrict this in real use — 0.0.0.0/0 is open to the world."
  type        = string
  default     = "0.0.0.0/0"
}

variable "secret_name" {
  description = "Name for the Secrets Manager secret that will hold the private key"
  type        = string
  default     = "jenkins-ec2-ssh-private-key"
}

############################################
# Key Pair — generated by Terraform, not borrowed from your personal SSH setup
############################################

resource "tls_private_key" "key_pair" {
  algorithm = "ED25519"
}

# Registers the generated PUBLIC key with AWS. Public keys aren't sensitive,
# so this is safe to keep in Terraform state / show in plan output.
resource "aws_key_pair" "my_app_instance_key" {
  key_name   = var.key_name
  public_key = tls_private_key.key_pair.public_key_openssh
}

############################################
# Store the PRIVATE key in AWS Secrets Manager — never in git, never in the
# Jenkins workspace, never in plan/apply console output.
############################################

resource "aws_secretsmanager_secret" "jenkins_ssh_private_key" {
  name        = var.secret_name
  description = "Private key for SSH access to the Jenkins EC2 instance"
}

resource "aws_secretsmanager_secret_version" "jenkins_ssh_private_key" {
  secret_id     = aws_secretsmanager_secret.jenkins_ssh_private_key.id
  secret_string = tls_private_key.key_pair.private_key_openssh
}

############################################
# Security Group
############################################

resource "aws_security_group" "sg" {
  name        = "my-app-instance-sg"
  description = "Allow SSH and Jenkins web UI access"

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_ssh_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

############################################
# EC2 Instance
############################################

# Always fetches the current latest Amazon Linux 2023 AMI at apply-time —
# equivalent to the `aws ssm get-parameters` step from the shell/pipeline version.
data "aws_ssm_parameter" "al2023_ami" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

resource "aws_instance" "my_app_server" {
  ami                    = data.aws_ssm_parameter.al2023_ami.value
  instance_type          = var.instance_type
  key_name               = aws_key_pair.my_app_instance_key.key_name
  vpc_security_group_ids = [aws_security_group.sg.id]

  tags = {
    Name = var.instance_name
  }
}

############################################
# Outputs
############################################

output "public_ip" {
  description = "Public IP address of the Jenkins EC2 instance"
  value       = aws_instance.my_app_server.public_ip
}

output "instance_id" {
  description = "EC2 instance ID"
  value       = aws_instance.my_app_server.id
}

output "secret_arn" {
  description = "ARN of the Secrets Manager secret holding the private key"
  value       = aws_secretsmanager_secret.jenkins_ssh_private_key.arn
}

output "ssh_command_hint" {
  description = "Reminder of how to retrieve the private key before SSHing in"
  value       = "aws secretsmanager get-secret-value --secret-id ${aws_secretsmanager_secret.jenkins_ssh_private_key.name} --query SecretString --output text > key.pem && chmod 400 key.pem && ssh -i key.pem ec2-user@${aws_instance.my_app_server.public_ip}"
}